[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file "$1"
"""

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e
cargo +1.85.0 test --locked --workspace
cargo +1.85.1 fmt --all --check
cargo +1.85.1 clippy --all-features --all-targets --locked --workspace -- -D warnings
cargo +1.85.1 test --locked --workspace
"""
